### ISSUE TITLE
Error when using wildcard **/*.js

### ISSUE THREAD

**Issue by gunar** [rstacruz/tape-watch#10]
Hi an thanks for tape-watch. I'm having a problem using it, though.

```
> medium-parser@0.0.1 test:watch /home/gcg/code/node_modules/medium-parser     
> tape-watch "lib/tests/**/*.js"                                               
                                                                               
Error: Cannot find module '/home/gcg/code/node_modules/medium-parser/lib/tests/
**/*.js'                                                                       
    at Function.Module._resolveFilename (module.js:339:15)                     
    at Function.Module._load (module.js:290:25)                                
    at Module.require (module.js:367:17)                                       
    at require (internal/module.js:16:19)                                      
    at /home/gcg/code/node_modules/medium-parser/node_modules/tape-watch/bin/ta
pe-watch:89:5                                                                  
    at invoke (/home/gcg/code/node_modules/medium-parser/node_modules/tape-watc
h/bin/tape-watch:69:10)                                                        
    at /home/gcg/code/node_modules/medium-parser/node_modules/tape-watch/bin/ta
pe-watch:47:10                                                                 
    at /home/gcg/code/node_modules/medium-parser/node_modules/tape-watch/lib/mu
tex.js:11:8                                                                    
    at call (/home/gcg/code/node_modules/medium-parser/node_modules/debounce-co
llect/index.js:29:19)                                                          
    at onTimeout [as _onTimeout] (/home/gcg/code/node_modules/medium-parser/nod
e_modules/debounce-collect/index.js:22:20)                                     
TAP version 13                                                                 
```

**Comment by gunar** [comment]
btw the test gets evaluated alright, it's just that see this annoying error message on every iterations.

**Comment by rstacruz** [comment]
oh.. hmm, i don't think that's supported because:

- `**/*.js` is evaluated by your shell. unless you're using a shell that supports double stars (like zsh or fish), it won't do what you expect it to.

- tape-watch only supports passing one file at the moment.

try making a file like `test.js` that require()'s your other tests individually.

**Comment by gunar** [comment]
Oh, fair enough. Thank you!
