### ISSUE TITLE
use babel-node?

### ISSUE THREAD

**Issue by veggiemonk** [rstacruz/tape-watch#16]
This is a great project!
I just don't know how to use this with babel.
I tried using `import 'babel-polyfill';` but it failed:
```
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /home/veggiemonk/code/waps/node_modules/tape-watch/bin/tape-watch:89:5
    at invoke (/home/veggiemonk/code/waps/node_modules/tape-watch/bin/tape-watch:69:10)
    at /home/veggiemonk/code/waps/node_modules/tape-watch/bin/tape-watch:47:10
TAP version 13

1..0
# tests 0
# pass  0

# ok
^C
```

Any idea?

**Comment by rstacruz** [comment]
Thanks for the report! #15 discusses this exact use case.

**Comment by veggiemonk** [comment]
Thank you. Sorry for the duplicate :blush:
