### ISSUE TITLE
Require assumes we are requiring from `node_modules` folder

### ISSUE THREAD

**Issue by chrisnicola** [rstacruz/tape-watch#204]
I run my tape tests like this: `tape -r ./src/test_helper src/**/*.test.js`

I load babel and some other test bootstrappy stuff in that file. This works with the tape runner but with `tape-watch` I get:

```
$ tape-watch src/**/*.test.js -p tap-spec -c --require ./src/test_helper
module.js:487
    throw err;
    ^

Error: Cannot find module '/Users/chrisnicola/src/myproject/node_modules/src/test_helper'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at requireHere (/Users/chrisnicola/src/wealthbar.api.billing/node_modules/tape-watch/bin/tape-watch:118:10)
    at /Users/chrisnicola/src/wealthbar.api.billing/node_modules/tape-watch/bin/tape-watch:165:5
    at Array.forEach (native)
    at requireMany (/Users/chrisnicola/src/wealthbar.api.billing/node_modules/tape-watch/bin/tape-watch:163:20)
    at Object.<anonymous> (/Users/chrisnicola/src/wealthbar.api.billing/node_modules/tape-watch/bin/tape-watch:51:3)
    at Module._compile (module.js:569:30)
error Command failed with exit code 1.
```

Ideally the require flag should follow the standard node module lookup patters from `process.cwd` as the location.

**Comment by refactorized** [comment]
I am actually getting similar behavior with plain in-source calls to require()

**Comment by mdix** [comment]
Same issue here. Having some local setup code for my tape tests which I need to require but `tape-watch` tries to require from `node_modules`.

**Comment by refactorized** [comment]
tumbleweeds... (not judging, people get busy) 

I used nodemon to execute a simple test runner I wrote which runs tape, tape-tape run, etc using their programatic api - the point is nodemon + some tooling = perfectly good watch solution.

**Comment by bennypowers** [comment]
You may apply this patch using [`patch-package`](https://www.npmjs.com/package/patch-package) (for example, in post-install). Just add `patches/tape-watch+2.3.0.patch` to your project root
```patch
patch-package
--- a/node_modules/tape-watch/bin/tape-watch
+++ b/node_modules/tape-watch/bin/tape-watch
@@ -115,7 +115,7 @@ var invoke = function (options) {
  */
 
 function requireHere (pkg) {
-  return require(path.join(cwd, 'node_modules', pkg))
+  return require(path.join(cwd, pkg.includes('.') ? '' : 'node_modules', pkg))
 }
 
 /*

```
