### ISSUE TITLE
Support esm

### ISSUE THREAD

**Issue by bennypowers** [rstacruz/tape-watch#211]
Hello and thank you for publishing this useful package.

I'd like to run tape-watch with the esm polyfill:

```json
  "scripts": {
    "watch": "tape-watch -r esm test/test.js -p tap-summary",
    "test": "tape -r esm test/test.js | tap-summary"
  }
```

However, I get this output:

```
# Tests
/path/to/test/test.js:1
(function (exports, require, module, __filename, __dirname) { import test from 'tape';
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at wrapSafe (internal/modules/cjs/loader.js:1057:15)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

**Comment by evanplaice** [comment]
See: [@vanillaes/tape-es](https://www.npmjs.com/package/@vanillaes/tape-es)
